<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common.Test\Readarr.Common.Test.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Common\Readarr.Test.Common.csproj" />
    <ProjectReference Include="..\..\src\NzbDrone.Windows\Readarr.Windows.csproj" />
  </ItemGroup>
</Project>
