<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NLog" />
    <PackageReference Include="NLog.Targets.ConcurrentFile" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="RestSharp" />
    <PackageReference Include="RestSharp.Serializers.SystemTextJson" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NzbDrone.Common\Readarr.Common.csproj" />
    <ProjectReference Include="..\..\src\NzbDrone.Core\Readarr.Core.csproj" />
  </ItemGroup>
</Project>
